### ISSUE TITLE
日程を決める

### ISSUE THREAD

**Issue by FromAtom** [KMSJ/KMSJ#1]

**Comment by umisama** [comment]
日程候補はこの辺ですかね？
酒を飲むので、出来れば土曜日の方が都合がよいかもしれない。

- 2/13
- 2/14
- 2/20
- 2/21

**Comment by FromAtom** [comment]
11日とかも祝日なので使えそう（翌日金曜日だけど）

**Comment by umisama** [comment]
流石に翌日が祝日はしんどい気がする

**Comment by umisama** [comment]
[![Vote](http://voting-badge.herokuapp.com/img?url=http://google.com)](http://voting-badge.herokuapp.com/vote?url=http://google.com)

**Comment by umisama** [comment]
[![Vote](http://voting-badge.herokuapp.com/img?url=https://github.com/KMSJ/KMSJ/issues/1)](http://voting-badge.herokuapp.com/vote?url=https://github.com/KMSJ/KMSJ/issues/1)

**Comment by FromAtom** [comment]
確かに

**Comment by setsuna82001** [comment]
土曜がいいなーヾ(｡>◡<)ﾉ"

**Comment by umisama** [comment]
いっそ2月の最終週、2/27(土曜日)でいかがでしょうか？

**Comment by umisama** [comment]
2/27でFIXです。
