### ISSUE TITLE
会場を決める

### ISSUE THREAD

**Issue by FromAtom** [KMSJ/KMSJ#2]

**Comment by umisama** [comment]
イロイロ考えてみましたが、やっぱりどこもそれなりに値段がしますね。
最小パターンだと、20人くらいの大きめカラオケボックスを借りてそこでやるのも良いかもしれないですね。

**Comment by umisama** [comment]
日程決まったらイロイロ問い合わせてみます。

**Comment by FromAtom** [comment]
カラオケボックス良さそう
